### ISSUE TITLE
If i'm using glob mask like icons/**/*.svg webpack-svgstore-plugin adds icons/*.svg to files list

### ISSUE THREAD

**Issue by limpbrains** [mrsum/webpack-svgstore-plugin#40]
to fix this add `{nodir: true}` to glob options,
I can create pull request, if you wish.

**Comment by lgordey** [comment]
@limpbrains 
I think it can be done like passing svgo options in plugin.
Pull request would be great! :)

**Comment by limpbrains** [comment]
It fails when it tries to read file in utils.js in readFileSync
```
fs.js:651
  var r = binding.read(fd, buffer, offset, length, position);
                  ^

Error: EISDIR: illegal operation on a directory, read
    at Error (native)
    at Object.fs.readSync (fs.js:651:19)
    at Object.fs.readFileSync (fs.js:472:24)
    at /home/limpbrains/bitlish/conceptstatic/node_modules/webpack-svgstore-plugin/helpers/utils.js:220:29
    at Array.forEach (native)
    at Object._parseFiles [as parseFiles] (/home/limpbrains/bitlish/conceptstatic/node_modules/webpack-svgstore-plugin/helpers/utils.js:218:9)
    at /home/limpbrains/bitlish/conceptstatic/node_modules/webpack-svgstore-plugin/index.js:91:50
    at /home/limpbrains/bitlish/conceptstatic/node_modules/webpack-svgstore-plugin/index.js:62:7
    at f (/home/limpbrains/bitlish/conceptstatic/node_modules/webpack-svgstore-plugin/node_modules/once/once.js:17:25)
    at Glob.<anonymous> (/home/limpbrains/bitlish/conceptstatic/node_modules/webpack-svgstore-plugin/node_modules/glob/glob.js:133:7)
    at emitOne (events.js:77:13)
    at Glob.emit (events.js:169:7)
    at Glob._finish (/home/limpbrains/bitlish/conceptstatic/node_modules/webpack-svgstore-plugin/node_modules/glob/glob.js:172:8)
    at done (/home/limpbrains/bitlish/conceptstatic/node_modules/webpack-svgstore-plugin/node_modules/glob/glob.js:159:12)
    at Glob._processReaddir2 (/home/limpbrains/bitlish/conceptstatic/node_modules/webpack-svgstore-plugin/node_modules/glob/glob.js:409:12)
    at /home/limpbrains/bitlish/conceptstatic/node_modules/webpack-svgstore-plugin/node_modules/glob/glob.js:346:17
```

**Comment by mrsum** [comment]
I've been apply your pull request. Can i close this issue?

**Comment by mrsum** [comment]
@limpbrains

**Comment by lgordey** [comment]
@limpbrains try 2.1.3 version
